### ISSUE TITLE
Number of epochs to train

### ISSUE THREAD

**Issue by ivanpuhachov** [OhataKenji/SketchRNN-Pytorch#8]
Nice repository, thank you.

Could you please indicate how many epochs of training did it take to generate that apple from `readme`? 
In the main branch `test.py` I see 300,000 epochs, `exp1.py` uses 3,000, `test.py` in experimental branch uses 300.

**Comment by OhataKenji** [comment]
Thank you for visiting my repository.

`test.py` is only for testing whether the code is working.
I remember vaguely 3000 epoch is enough

P.S.
I just merged exp branch which is newer into main branch.

**Comment by ivanpuhachov** [comment]
Thanks for answering!
I trained `test.py` overnight, and after 1000 epochs it is far from convergence.
One epoch of `exp1.py` takes 3 minutes on my 2080ti, I'll see how I can make it work.

For those coming after me, this is tensorboard metrics I had after a 1000 epochs of `test.py`
![image](https://user-images.githubusercontent.com/49251289/112653007-65093080-8e24-11eb-9b7c-add0f7dd43d0.png)
![image](https://user-images.githubusercontent.com/49251289/112653043-6e929880-8e24-11eb-826c-07f9ee75402b.png)

**Comment by OhataKenji** [comment]
Sorry.
There was a bug in old master branch.
(At that time, I was working on exp branch and lazy to merge into master)

Please `git pull` (or checkout to exp branch)
and try it again.

**Comment by ivanpuhachov** [comment]
Oh, I realised that I had a bug in dataset preprocessing - I did some version-related fixes to your code and my implementation had a bug.

Do you mind if I do a PR with fixes for newer version of pytorch afterwards?

**Comment by OhataKenji** [comment]
Ok.
I'm happy that you're willing to PR to my repository.

However, Pytorch is being developed actively
and it's tedious to keep the code available in every stable version.
Currently, its reproducibility (related library versions) is ensured by Dockerfile.
So, I think version related fix is not necessary. 

(Please tell me if you have different ideas)

**Comment by ivanpuhachov** [comment]
You are right. I started new training and the results seems much nicer now. I'll post tensorboard images once it reaches 100 epochs, for reproducibility sake.

The issue can be closed. Thank you for your help!

**Comment by ivanpuhachov** [comment]
Some learning curves and reconstruction results. Hit `nan` at epoch 562, but that could be fixed by clipping some values, i.e.rho to fix 1 / (1 - rho**2)

![image](https://user-images.githubusercontent.com/49251289/112763141-311f3e00-8fd1-11eb-8a1f-e9bcefa390cb.png)
![image](https://user-images.githubusercontent.com/49251289/112763208-852a2280-8fd1-11eb-8837-b1d3396086e2.png)
